In [0]:
from __future__ import print_function
import torch
import numpy as np

# 1.Getting Started With Pytorch

```
from __future__ import print_function
import torch
```
## 1.1 What is Pytorch?
[document](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

Pytorch is an open source machine learning framework that accelerates the path from research prototyping to production deployment.

## 1.2 Basic knowledge

### 1.2.1 Tensors
[Document](https://pytorch.org/docs/stable/tensors.html)
* Tensors are similar to NumPy’s ndarrays
* Tensors can be used on a GPU to accelerate computing.

#### torch.Tensor
A ```torch.Tensor``` is a multi-dimensional matrix containing elements of a **single data type**.

* Data type:
 * There are **9** different data types available:
 * ```torch.double```
 * ```torch.int```
 * ```torch.bool```
 * ...
* CPU/GPU
 * Tensor can be either CPU tensor or GPU tensor

So there are $2*9=18$ different types of tensor.

```torch.Tensor``` is an alias for the default tensor type (torch.FloatTensor)

### 1.2.2 Creating a tensor in PyTorch

* Declare an uninitialized matrix with unknown values.
```
x = torch.empty(5, 3)
```
* Construct a randomly initialized matrix(uniform(0,1) random variables):
```
x = torch.rand(5, 3)
```
* Construct a matrix filled zeros and of dtype long:
```
x = torch.zeros(5, 3, dtype=torch.long)
```
* Construct a tensor directly from data(from a Python ```1ist```):
```
x = torch.tensor([[1., -1.], [1., -1.]])
x = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
```
* Construct a tensor using numpy array: ```torch.tensor() ``` always copies(deep copy) ```data```. If you want to avoid a copy, use ```torch.as_tensor()```.:
```
x = torch.tensor([[1., -1.], [1., -1.]])
y = torch.tensor(x)
z = torch.as_tensor(x)
```
  These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user.
 * ```new_*``` methods. Create a tensor with similar type but different size as another tensor.
 ```
x = x.new_ones(5, 3, dtype=torch.double)
 ```
 * ```torch.*_like``` methods. Create a tensor with the same size (and similar types) as another tensor.
 ```
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
 ```

### 1.2.3 Some Operations
[Document about operators](https://pytorch.org/docs/stable/torch.html)
* Get size: ```size()```



In [0]:
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


* Addition
 * ```+```
 * ```torch.add()```
 * ```tensor.add_()```

In [0]:
x = torch.tensor([[0,0],[10,10]])
y = torch.rand(2, 2)

print(x + y)

print(torch.add(x, y))

# providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# adds x to y
y.add_(x)
print(y)

tensor([[ 0.1443,  0.4542],
        [10.0129, 10.4402]])
tensor([[ 0.1443,  0.4542],
        [10.0129, 10.4402]])
tensor([[ 0.1443,  0.4542],
        [10.0129, 10.4402]])
tensor([[ 0.1443,  0.4542],
        [10.0129, 10.4402]])


> Note: Any operation that mutates a tensor in-place is post-fixed with an ```_```. For example: ```x.copy_(y)```, ```x.t_()```, will change x

*  NumPy-like indexing can be used.

In [0]:
print(x[:, 1])

tensor([ 0, 10])


* resize/reshape tensor: ```torch.view``` or ```torch.reshape```

In [0]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
w = x.reshape(2,-1)
print(x.size(), y.size(), z.size(), w.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([2, 8])


* Get the value of an one-element tensor: ```.item()```

In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5503])
-0.5503179430961609


## 1.3 NumPy Bridge

It is easy to converte a Torch Tensor to a NumPy array and vice versa.

* Torch Tensor to NumPy Array: ```tensor.numpy()```
 * The ndarray and tensor share the same value.
 * All the Tensors on the CPU except a CharTensor support converting to NumPy and back.


In [0]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

# They change in value simultaneously.
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## 1.3 CUDA Tensors

Tensors can be moved onto any device using the ```.to``` method.


In [0]:
x = torch.randn(1)
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    print("y on GPU:\n ",y)
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    print("x moved to GPU:\n ",x)
    z = x + y
    print("z= x+ y on GPU:\n",z)
    print("move z to CPU:\n",z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

y on GPU:
  tensor([1.], device='cuda:0')
x moved to GPU:
  tensor([-0.3136], device='cuda:0')
z= x+ y on GPU:
 tensor([0.6864], device='cuda:0')
move z to CPU:
 tensor([0.6864], dtype=torch.float64)
